### ISSUE TITLE
Server not found with newest beta

### ISSUE THREAD

**Issue by marzzzello** [kriztan/Pix-Art-Messenger#445]
#### General information
I installed the beta and restored the data via Titanium Backup. I have multiple profiles from different servers. The problem just appears with one server. I also tried a fresh install without restoring and the same problem appears.

EDIT:
I narrowed down the problem:
Working: `2.3.5.3-04755 beta (2020-02-02)`
Not Working: `2.3.5.3-04756 beta (2020-02-02)`

* **Version:** 2.3.5.5-04766 beta (2020-02-07)
* **Device:** OnePlus 3
* **Android Version:** Android 9 LineageOS

#### Steps to reproduce

1. Deactivate all profiles
2. Activate the problematic profile
3. Wait & copy log

#### Expected result
No connection problems

#### Actual result
`Server nicht gefunden`

#### Debug output

````
02-08 00:23:10.092  6037  6037 D Pix-Art_Messenger: XX@ruhr-uni-bochum.de: error connecting account. reconnecting now. lowPingTimeout=false
02-08 00:23:10.103  6037  6390 D Pix-Art_Messenger: XX@ruhr-uni-bochum.de: connecting
02-08 00:23:10.131  6037  6390 D Pix-Art_Messenger: XX@ruhr-uni-bochum.de: error connecting account. try again in 32s for the 2 time. lowPingTimeout=false
02-08 00:23:10.148  6037  6037 D Pix-Art_Messenger: ForegroundService: on
02-08 00:23:10.206  6037  6397 D Pix-Art_Messenger: XX@ruhr-uni-bochum.de: connecting
02-08 00:23:10.417  6037  6397 D Pix-Art_Messenger: Resolver: [Result{ip='2a05:3e00:1:1002::64:10', hostame='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}, Result{ip='134.147.64.10', hostame='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}]
02-08 00:23:10.424  6037  6412 D Pix-Art_Messenger: Resolver: Result disconnect: Result{ip='2a05:3e00:1:1002::64:10', hostame='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}
02-08 00:23:10.426  6037  6413 D Pix-Art_Messenger: Resolver: Result disconnect: Result{ip='134.147.64.10', hostame='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: Resolver: happy eyeball failed: 
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.net.Socket.isConnected()' on a null object reference
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at java.util.concurrent.AbstractExecutorService.doInvokeAny(AbstractExecutorService.java:199)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at java.util.concurrent.AbstractExecutorService.invokeAny(AbstractExecutorService.java:220)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at de.pixart.messenger.utils.Resolver.happyEyeball(Resolver.java:276)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at de.pixart.messenger.utils.Resolver.resolve(Resolver.java:146)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at de.pixart.messenger.xmpp.XmppConnection.connect(XmppConnection.java:325)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at de.pixart.messenger.xmpp.XmppConnection.run(XmppConnection.java:451)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at java.lang.Thread.run(Thread.java:764)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.net.Socket.isConnected()' on a null object reference
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at de.pixart.messenger.utils.Resolver$Result.call(Resolver.java:432)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at de.pixart.messenger.utils.Resolver$Result.call(Resolver.java:306)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-08 00:23:10.431  6037  6397 E Pix-Art_Messenger: 	... 1 more
02-08 00:23:10.431  6037  6397 D Pix-Art_Messenger: XX@ruhr-uni-bochum.de: error connecting account. try again in 42s for the 3 time. lowPingTimeout=false
02-08 00:23:11.266  6037  6068 D Pix-Art_Messenger: found 1860 changed files on start up. total=8753. (25655ms)
02-08 00:23:13.134  6037  6037 D Pix-Art_Messenger: toggle forced foreground service after receiving event (action=de.pixart.messenger.POST_CONNECTIVITY_CHANGE)

````

**Comment by genofire** [comment]
thank you for you nice log - it helps alot

**Comment by kriztan** [comment]
it is fixed with the latest beta

**Comment by marzzzello** [comment]
I still get server not found. But the java exception is gone
```
02-09 20:12:03.324 24824 24824 D Pix-Art_Messenger: ForegroundService: on
02-09 20:12:03.337 24824 24948 D Pix-Art_Messenger: XX@ruhr-uni-bochum.de: connecting
02-09 20:12:03.984 24824 24948 D Pix-Art_Messenger: Resolver: happy eyeball (3fbfdba7cd240408) with [Result{ip='2a05:3e00:1:1002::64:10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}, Result{ip='134.147.64.10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}]
02-09 20:12:03.994 24824 24973 D Pix-Art_Messenger: Resolver: Result disconnect: Result{ip='2a05:3e00:1:1002::64:10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}
02-09 20:12:11.017 24824 24974 D Pix-Art_Messenger: Resolver: Result disconnect: Result{ip='134.147.64.10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}
02-09 20:12:11.018 24824 24948 I Pix-Art_Messenger: Resolver: happy eyeball (3fbfdba7cd240408) unable to connect to one address
02-09 20:12:11.020 24824 24948 D Pix-Art_Messenger: XX@ruhr-uni-bochum.de: error connecting account. try again in 25s for the 2 time. lowPingTimeout=false
02-09 20:12:21.574 24824 24874 D Pix-Art_Messenger: found 1860 changed files on start up. total=8754. (26228ms)
02-09 20:12:37.037 24824 24824 D Pix-Art_Messenger: toggle forced foreground service after receiving event (action=de.pixart.messenger.POST_CONNECTIVITY_CHANGE)
02-09 20:12:37.052 24824 24824 D Pix-Art_Messenger: ForegroundService: on
02-09 20:12:37.055 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:12:37.073 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:12:37.074 24824 25038 D Pix-Art_Messenger: XX@ruhr-uni-bochum.de: connecting
02-09 20:12:37.074 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:12:37.074 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:12:37.174 24824 24824 D Pix-Art_Messenger: toggle forced foreground service after receiving event (action=ping)
02-09 20:12:37.186 24824 24824 D Pix-Art_Messenger: ForegroundService: on
02-09 20:12:37.189 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:12:37.201 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:12:37.441 24824 25038 D Pix-Art_Messenger: Resolver: happy eyeball (3feedd1f1c9165b3) with [Result{ip='2a05:3e00:1:1002::64:10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}, Result{ip='134.147.64.10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}]
02-09 20:12:37.451 24824 25051 D Pix-Art_Messenger: Resolver: Result disconnect: Result{ip='2a05:3e00:1:1002::64:10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}
02-09 20:13:03.771 24824 24824 D Pix-Art_Messenger: app switched into background
02-09 20:13:07.465 24824 25052 D Pix-Art_Messenger: Resolver: Result disconnect: Result{ip='134.147.64.10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}
02-09 20:13:07.467 24824 25038 I Pix-Art_Messenger: Resolver: happy eyeball (3feedd1f1c9165b3) unable to connect to one address
02-09 20:13:07.475 24824 25038 D Pix-Art_Messenger: XX@ruhr-uni-bochum.de: error connecting account. try again in 12s for the 3 time. lowPingTimeout=false
02-09 20:13:20.483 24824 24824 D Pix-Art_Messenger: toggle forced foreground service after receiving event (action=ping)
02-09 20:13:20.495 24824 24824 D Pix-Art_Messenger: ForegroundService: on
02-09 20:13:20.498 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:13:20.499 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:13:20.515 24824 25174 D Pix-Art_Messenger: XX@ruhr-uni-bochum.de: connecting
02-09 20:13:20.522 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:13:20.525 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:13:20.748 24824 25174 D Pix-Art_Messenger: Resolver: happy eyeball (3fe2c5193b0e902b) with [Result{ip='2a05:3e00:1:1002::64:10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}, Result{ip='134.147.64.10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}]
02-09 20:13:20.757 24824 25186 D Pix-Art_Messenger: Resolver: Result disconnect: Result{ip='2a05:3e00:1:1002::64:10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}
02-09 20:13:21.668 24824 24824 D Pix-Art_Messenger: app switched into foreground
02-09 20:13:21.678 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:13:21.687 24824 24824 D Pix-Art_Messenger: Number of accounts is 5
02-09 20:13:23.768 24824 25187 D Pix-Art_Messenger: Resolver: Result disconnect: Result{ip='134.147.64.10', hostname='ruhr-uni-bochum.de', port=5222, directTls=false, authenticated=false, priority=0}
02-09 20:13:23.769 24824 25174 I Pix-Art_Messenger: Resolver: happy eyeball (3fe2c5193b0e902b) unable to connect to one address
02-09 20:13:23.770 24824 25174 D Pix-Art_Messenger: XX@ruhr-uni-bochum.de: error connecting account. try again in 51s for the 4 time. lowPingTimeout=false

```

**Comment by kriztan** [comment]
Thanks @marzzzello. I hope @genofire is able to fix this.

**Comment by genofire** [comment]
okay, that is a strange error but wrong handling of dns.
it should be other IP-Adresses:
```
$ dig +short _xmpps-client._tcp.ruhr-uni-bochum.de SRV
10 0 5223 jabber.ruhr-uni-bochum.de.

$ dig +short _xmpp-client._tcp.ruhr-uni-bochum.de SRV 
10 0 5222 jabber.ruhr-uni-bochum.de.

$ host jabber.ruhr-uni-bochum.de 
jabber.ruhr-uni-bochum.de is an alias for jabber.mail.ruhr-uni-bochum.de.
jabber.mail.ruhr-uni-bochum.de has address 134.147.53.146
jabber.mail.ruhr-uni-bochum.de has IPv6 address 2a05:3e00:8:1001:5054:ff:fed3:dabb
```

**Comment by marzzzello** [comment]
I did not change anything at dns. With DoH I get same results.
The IPs are not from the jabber subdomain but from the main domain:
```
$ host ruhr-uni-bochum.de       
ruhr-uni-bochum.de has address 134.147.64.10
ruhr-uni-bochum.de has IPv6 address 2a05:3e00:1:1002::64:10
ruhr-uni-bochum.de mail is handled by 10 mi.ruhr-uni-bochum.de.
```

**Comment by genofire** [comment]
Okay, i found the wrong part - your DNS-Entries are not conform (a fallback was removed :/ ).

[RFC for DNS-SRV](https://tools.ietf.org/html/rfc2782) - in your target of the server entry it is not allowed to set enter a ALIAS / CNAME.

To fix it at `ruhr-uni-bochum.de` there are two ways (till a fallback is available again) and be RFC comform:
1. change SRV to `jabber.mail.ruhr-uni-bochum.de`
1. change  `jabber.ruhr-uni-bochum.de` from CNAME to A and AAAA ... (without "2" alias steps)

**Comment by marzzzello** [comment]
This is not my server but I can talk with the admin to get the dns fixed.
Why did it work before but not with the beta?

**Comment by genofire** [comment]
refactoring during handle happy eyeball of dns was also necessary - and was dropped, because it was declared of deadcode (in purpose of RFCs)

if this change, please give feedback - it is nice for testing a new fallback implement.

**Comment by marzzzello** [comment]
Does the fallback get implemented until release?
